FROM openjdk:11-jre-slim

COPY ./jag-crdp-process-transformer/target/jag-crdp-process-transformer.jar jag-crdp-process-transformer.jar

ENTRYPOINT ["java", "-jar","/jag-crdp-process-transformer.jar"]
